### PR TITLE
Updates for 0.18.x

### PR DESCRIPTION
**Pull request by pierre**
Note: I've only verified that the tests pass and that the plugin works properly with the `NullTaxResolver`. More regression testing is required.

Related to https://github.com/bgandon/killbill-simple-tax-plugin/issues/2 (users on 0.16.x are encouraged to migrate to 0.18.x). /cc @adamlc

### CODE REVIEW

**Comment by bgandon** [comment]
Cool, thanks mec!
I'm currently on vacation but I'm sure I can find some time for a closer look at this. ;-)
Having had a quick look already, I can say this might be enough because I remember the `dryRun` flag thing and that very few changes were actually required for the 0.16.x branch compatibility.
Cheers

**Comment by skuda** [comment]
@bgandon  This should be merged, no? 

I am evaluating Killbill and this plugin would help us, thanks!.
I think it's going to be easy to integrate our VAT rules using that plugin, but we need to use it with Killbill 0.18.

**Comment by GregOriol** [comment]
@pierre Any plans to merge this PR?

**Comment by pierre** [comment]
@GregOriol It looks like this plugin has been abandoned. @skuda however has started a new project (details on the [mailing-list](https://groups.google.com/forum/#!msg/killbilling-users/eeCETtJ7iS0/uRcbsEytAQAJ)). Not sure if it's public already, I'll let him jump in.

**Comment by skuda** [comment]
Hi, not public yet, we are finishing it, it will be public in about 2 weeks.

**Comment by bgandon** [comment]
Well, sorry for the delay guys. And no @pierre, this plugin is not abandoned.

Actually, there were breaking changes that were pending. I finished the related refactoring a few days ago. The impact is that the tax-related "taxCountry" fields (account level) are renamed "taxZone".

I wanted to finish that first, before anyone starts using the now-deprecated "taxCountry" fields in production, so that we can avoid setting up detailed (and maybe tedious) migration path.

Now the plan is to update this plugin to newer killbill version (i.e. merge this PR), then chose one of those two paths:

1. You already have started using "taxCountry" fields in production, so we publish this plugin as-is with "taxCountry" fields as stable v1.0, and we publish the "taxZone" refactoring as v2.0. The we would have to figure out a migration path from v1.0 to v2.0.
2. You have no production data with "taxCountry" fields. So we integrate the "taxZone" refactoring into the v1.0 branch and we publish this plugin right away with "taxZone".

Could you guys give me some feedback about those two options please?
Thanks.

**Comment by bgandon** [comment]
For you to have a chance to see the impact, I just published the "taxZone" refactoring in a separate "refactor-taxCountry-into-taxZone" feature branch.

**Comment by skuda** [comment]
Those are awesome news!! A lot of people is using that plugin! 
Thanks @bgandon :-)

**Comment by pierre** [comment]
FYI, Kill Bill 0.20 has now been released, our latest LTS version. Additional work would be required to make the plugin run with that version.

**Comment by bgandon** [comment]
Ok, thank you @pierre the the heads-up.

**Comment by pierre** [comment]
Hi all,

Closing this PR as I now have a working version of the plugin for Kill Bill 0.22.x [here](https://github.com/pierre/killbill-simple-tax-plugin/).

Step-by-step setup instructions can be found [here](https://github.com/pierre/killbill-simple-tax-plugin/blob/7e8b5852101ecdcf6ec858b9265e85c316dab286/README.md#testing).

**Pull request closed without merging**
